name: CI
on:
  push:
    branches: [main, master]
    tags: ["*"]
  pull_request:
  schedule:
    - cron: '0 0 * * 1'
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1'
          - 'min'
          - 'pre'
          - 'nightly'
        os:
          - ubuntu-latest
          - windows-latest
        arch:
          - x64
        include:
          - os: macOS-latest
            arch: aarch64
            version: '1'
          - os: macOS-latest
            arch: aarch64
            version: min
          - os: macOS-latest
            arch: aarch64
            version: pre
          - os: macOS-latest
            arch: aarch64
            version: nightly
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/cache@v2
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
